CREATE TABLE PEDIDOS (
    SITUACAO VARCHAR(25),
    FK_CLIENTE INTEGER,
    VALOR_FRETE DECIMAL(15,2),
    CODIGO_PED SMALLINT);

    
CREATE TABLE CLIENTES (
    NOME VARCHAR(70),
    CPF_CNPJ VARCHAR(15),
    CIDADE VARCHAR(50),
    UF VARCHAR(2),
    CODIGO_CLI SMALLINT);

    CREATE TABLE ITENS_PEDIDOS (
    CODIGO_ITEM INTEGER,
    PRODUTO INTEGER,
    PEDIDO INTEGER,
    QUANTIDADE DECIMAL(18,2),
    DESCONTO DECIMAL(18,2),
    STATUS VARCHAR(25),
    TIPO VARCHAR(10));

    CREATE TABLE PRODUTOS (
    DESCRICAO VARCHAR(70),
    CODIGO_BARRAS VARCHAR(255),
    QUANTIDADE DECIMAL(15,2),
    UNIDADE VARCHAR(4),
    CUSTO_UNITARIO DECIMAL(15,2),
    PRECO_VENDA DECIMAL(15,2),
    CODIGO_PROD SMALLINT);

    INSERT INTO PRODUTOS (DESCRICAO, CODIGO_BARRAS, QUANTIDADE, UNIDADE, CUSTO_UNITARIO, PRECO_VENDA, CODIGO_PROD)
              VALUES ('Produto A', '7891038195102', 2, 'Und', 10, 15, 1);
INSERT INTO PRODUTOS (DESCRICAO, CODIGO_BARRAS, QUANTIDADE, UNIDADE, CUSTO_UNITARIO, PRECO_VENDA, CODIGO_PROD)
              VALUES ('Produto B', '7894900031157', 0, 'KG', 5, 7.55, 2);
INSERT INTO PRODUTOS (DESCRICAO, CODIGO_BARRAS, QUANTIDADE, UNIDADE, CUSTO_UNITARIO, PRECO_VENDA, CODIGO_PROD)
              VALUES ('Produto C', '7891000284933', 4, 'LT', 20, 22.33, 3);
INSERT INTO PRODUTOS (DESCRICAO, CODIGO_BARRAS, QUANTIDADE, UNIDADE, CUSTO_UNITARIO, PRECO_VENDA, CODIGO_PROD)
              VALUES ('Produto D', '7891959001452', 5, 'PC', 2.5, 3, 4);
INSERT INTO PRODUTOS (DESCRICAO, CODIGO_BARRAS, QUANTIDADE, UNIDADE, CUSTO_UNITARIO, PRECO_VENDA, CODIGO_PROD)
              VALUES ('Produto E', '7896028014494', 1, 'KG', 10.89, 12.99, 5);

INSERT INTO PEDIDOS (SITUACAO, FK_CLIENTE, VALOR_FRETE, CODIGO_PED)
             VALUES ('Pendente', 2, 0, 1);
INSERT INTO PEDIDOS (SITUACAO, FK_CLIENTE, VALOR_FRETE, CODIGO_PED)
             VALUES ('Faturado', 3, 10, 2);
INSERT INTO PEDIDOS (SITUACAO, FK_CLIENTE, VALOR_FRETE, CODIGO_PED)
             VALUES ('Cancelado', 1, 2.55, 3);
INSERT INTO PEDIDOS (SITUACAO, FK_CLIENTE, VALOR_FRETE, CODIGO_PED)
             VALUES ('Pendente', 4, 0, 4);
INSERT INTO PEDIDOS (SITUACAO, FK_CLIENTE, VALOR_FRETE, CODIGO_PED)
             VALUES ('Pendente', 2, 20, 5);



INSERT INTO CLIENTES (NOME, CPF_CNPJ, CIDADE, UF, CODIGO_CLI)
              VALUES ('João da Silva', '772.975.980-20', 'Cascavel', 'PR', 1);
INSERT INTO CLIENTES (NOME, CPF_CNPJ, CIDADE, UF, CODIGO_CLI)
              VALUES ('Maria Lurdes', '885.270.660-76', 'Curitiba', 'PR', 2);
INSERT INTO CLIENTES (NOME, CPF_CNPJ, CIDADE, UF, CODIGO_CLI)
              VALUES ('Lucas dalponte', '511.971.430-76', 'Cascavel', 'MS', 3);
INSERT INTO CLIENTES (NOME, CPF_CNPJ, CIDADE, UF, CODIGO_CLI)
              VALUES ('Mateus Oliveira', '472.859.130-14', 'Petrópolis', 'RJ', 4);




INSERT INTO ITENS_PEDIDOS (CODIGO_ITEM, PRODUTO, PEDIDO, QUANTIDADE, DESCONTO, STATUS, TIPO)
                   VALUES (5, 1, 5, 2, 0, 'Não', 'S');
INSERT INTO ITENS_PEDIDOS (CODIGO_ITEM, PRODUTO, PEDIDO, QUANTIDADE, DESCONTO, STATUS, TIPO)
                   VALUES (4, 3, 4, 4, 2.5, 'Não', 'S');
INSERT INTO ITENS_PEDIDOS (CODIGO_ITEM, PRODUTO, PEDIDO, QUANTIDADE, DESCONTO, STATUS, TIPO)
                   VALUES (3, 5, 3, 2.5, 10, 'Sim', 'S');
INSERT INTO ITENS_PEDIDOS (CODIGO_ITEM, PRODUTO, PEDIDO, QUANTIDADE, DESCONTO, STATUS, TIPO)
                   VALUES (2, 3, 2, 10.3, 0, 'Não', 'S');
INSERT INTO ITENS_PEDIDOS (CODIGO_ITEM, PRODUTO, PEDIDO, QUANTIDADE, DESCONTO, STATUS, TIPO)
                   VALUES (1, 4, 1, 1, 0, 'Não', 'S');


-- J - Relatorio agrupando por cidade

SELECT distinct pedidos.*,   cidade , uf
  FROM clientes  inner join
  pedidos
  on clientes.codigo_cli = pedidos.fk_cliente
 where cidade like 'Cascavel' and uf like 'PR'



